### ISSUE TITLE
Number-keyed properties

### ISSUE THREAD

**Issue by uhyo** [nd-02110114/babel-plugin-object-to-json-parse#10]
Currently, this plugin cannot correctly convert number-keyed properties.

**before**

```js
const obj = {
  123: "123",
  45: 45
};

console.log(obj[123]); // => "123"
```

**after**

```js
const obj = JSON.parse('{"undefined":45}');
console.log(obj[123]); // => undefined
```

**Comment by nd-02110114** [comment]
Thank you for reporting!
Maybe, I fixed this issue by #13. 
Please confirm 🙇

**Comment by uhyo** [comment]
This is very good, but I have to mention one thing.

I've just noticed that converting number-keyed properties may change the meaning of programs because **the result of converting a number to a string using ToString is implementation-dependent** as per [the spec](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-tostring-applied-to-the-number-type).

Example:

```js
// before
var obj = {77777777777777777: "foo"};
console.log(obj[77777777777777777]); // => "foo"
```

this program outputs `"foo"` in all browsers.
However, the program after conversion behaves differently in **IE11**:

```js
// after
const obj1 = JSON.parse('{"77777777777777780":"foo"}');
console.log(obj1[77777777777777777]); // => "foo"
```

This program still outputs `"foo"` for Chrome, but IE11 shows `undefined` for the same program.

**Comment by uhyo** [comment]
It might be good to allow conversion of numeric keys if they are [safe integers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger).

**Comment by nd-02110114** [comment]
I fixed this issue by using `Number.isSafeInteger`. (#15 )
Can I close this issue?

**Comment by uhyo** [comment]
Seems very nice; thank you!
