### ISSUE TITLE
About prettier

### ISSUE THREAD

**Issue by uhyo** [nd-02110114/babel-plugin-object-to-json-parse#2]
Great work!
This repository includes `.prettierrc.js` but it seems to be unused.
Indeed, contents of this repository is not formatted by prettier.

My editor detects existence of `.prettierrc.js` and automatically formats the code I'm editing, which made me struggle while working on #1.
Please either enable prettier in this repository, or remove `.prettierrc.js`.

In addition, automatic linting on commit would be very nice.

Thank you!

**Comment by nd-02110114** [comment]
@uhyo 
Thank you for advising the prettier !!
I changed the setting by #3 , #4. Can I close this issue?

**Comment by uhyo** [comment]
These changes are very nice!
However, the source codes in `example/` and `test/` are not formatted by `prettier` now.
Could you either include these files to the target of prettier, or prepare `.prettierignore`  to ignore these files?

**Comment by nd-02110114** [comment]
I'm so sorry for the inconvenience. I prepared `.prettiierignore` by #8 
Please confirm 🙇

**Comment by uhyo** [comment]
No problem now!
Thank you for your effort on this kind of things.
Hope this nice project gets a lot of contributions.
