### ISSUE TITLE
Help answer why code need duplicate \t?

### ISSUE THREAD

**Issue by HillLiu** [nd-02110114/babel-plugin-object-to-json-parse#32]
## issue code
```
const codes = ['\t', '\f', '\r', '\n', '\t', '\b']
```
https://github.com/nd-02110114/babel-plugin-object-to-json-parse/blob/master/src/utils.ts#L79

@nd-02110114 
Could u clarify my doubt, I think it possible trigger double encode.

**Comment by nd-02110114** [comment]
This is my mistake... I quickly fix this code.

**Comment by nd-02110114** [comment]
I fixed at the commit https://github.com/nd-02110114/babel-plugin-object-to-json-parse/commit/33883cc7071ed86b82e68c99e813d3aeeb230e6b

**Comment by HillLiu** [comment]
Thanks @nd-02110114
