### ISSUE TITLE
Escaping only the 1st occurence

### ISSUE THREAD

**Issue by pauldijou** [nd-02110114/babel-plugin-object-to-json-parse#35]
I stumbled across a `JSON.parse` suddenly throwing and it seems that some `\n` are not properly escaped.

Reading the source code, it seems that because the `RegExp` is not using the global flag, it will only escape the 1st occurence and leaving the following ones as is. 

```javascript
  if (/[\t\f\r\n\b]/g.test(value)) {
    const codes = ['\f', '\r', '\n', '\t', '\b']
    const replaceCodes = ['\\f', '\\r', '\\n', '\\t', '\\b']
    for (let i = 0; i < codes.length; i++) {
      value = value.replace(new RegExp(codes[i]), replaceCodes[i])
    }
  }
```

For example;

```javascript
// Input
const foo = ['Test\nthis\nstuff];

// Output
const foo = JSON.parse('["Test\\nthis\nstuff"]');
```

Using `new RegExp(codes[i], 'g')` should probably solve it.

**Comment by nd-02110114** [comment]
Thank you for reporting the issue. I fixed #36
